const data = [
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
    'Lorem ipsum dolor sit amet consectetur adipisicing eLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,lit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,',
]
export default data;